name: Flow control
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: exit "$(( RNADOM % 2 ))"
      - run: exit 1
        id: error
      - run: echo "Catch error step"
        if: ${{ failure() && steps.error.outcome == 'failure' }}
